version: "3.8"
services:
  server:
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    expose:
      - 8000

  client:
    build:
      context: ./client/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8888:8888"
    expose:
      - 8888
